---
title: Alfred Tang
timezone: GMT+8
collections:
  posts:
    title: Drafts
    output: true
  uploads:
    title: Uploads
    output: true
description: A Portfolio
author: Alfred Tang
logo: "/static/img/avatar.png"
github: https://github.com/alfred1137
about: Associate Consultant - Corporate Sustainability
baseurl: ''
url: https://www.linkedin.com/in/alfred1137/
disqus_shortname: 
google_analytics: UA-93499097-1
share:
  twitter_username: "\\#"
  fb_appid: 0
enableTags: true
tagarray: []
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
- jekyll-paginate
- jekyll-gist
